apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  # num of pods running in eb image
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: torressam/event-bus:latest
          ports:
            - containerPort: 80
---
# Cluster up Service
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector:
    app: event-bus
  type: ClusterIP
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
